#!/usr/bin/env python3
"""gen-endpoint-set.py — the facts of EVERY endpoint, one file each, so the endpoint lab can open any of them (D-035).

The operator (2026-09-23): "Be able to change the endpoint for any of the other endpoints that we have here in the all
endpoints.html file." The lab is baked to ONE endpoint through `_lab-ep.js` (committed, the default). This builds the
others the same way — gen-endpoint-facts.py, once per endpoint, with --out — into `_eps/<slug>.js`, a LOCAL build that is
git-ignored (each file is several hundred KB; eighty of them are too heavy to commit and re-commit).

    cd docs/design/workflow-panel
    python3 gen-endpoint-set.py                         # every endpoint of the frozen lab feed → _eps/ + _lab-ep-index.js
    python3 gen-endpoint-set.py --index-only            # only the committed list of endpoints (_lab-ep-index.js)
    python3 gen-endpoint-set.py --only "GET /recipes/{recipe_id}"   # one endpoint (repeatable)
        --forms <file>     default ~/.cache/gabe-map-baselines/lab-input/forms.json (an arms-on build, the lab's feed)
        --archmap <file>   default: archmap.json beside --forms

WHAT IT WRITES
  _lab-ep-index.js  COMMITTED, small: every endpoint the feed holds — label, method, path, entity, the entity's colour and
                    the slug — so the lab's picker lists all of them whether or not their facts are built here.
  _eps/<slug>.js    LOCAL: one endpoint's facts, byte-for-byte what gen-endpoint-facts.py writes for it.
  _eps/built.js     LOCAL: the list of the facts files present in _eps/ and the feed head each was built at — the picker
                    reads it to mark an endpoint "not built here". Re-derived from the directory on every run.
The slug is _ep-slug.js's rule, run under node — never restated here. `_lab-ep.js` is never written: its sha1 is taken
before and after, and a change stops the build.
"""
from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
FACTS = HERE / "gen-endpoint-facts.py"
SLUG_JS = HERE / "_ep-slug.js"
LAB = HERE / "_lab-ep.js"
EPS = HERE / "_eps"
INDEX = HERE / "_lab-ep-index.js"
C4 = REPO / "templates" / "center" / "shell" / "example" / "codebase-graph-station" / "c4-graph.js"
DEF_FORMS = Path("~/.cache/gabe-map-baselines/lab-input/forms.json")
HEAD_RX = re.compile(r"\(head ([0-9a-f]+)\)")


def die(msg: str) -> None:
    print("gen-endpoint-set: " + msg, file=sys.stderr)
    sys.exit(1)


def arg(argv: list, name: str, default=None, many=False):
    got = []
    while name in argv:
        i = argv.index(name)
        if i + 1 >= len(argv):
            die(f"{name} needs a value")
        got.append(argv[i + 1]); del argv[i:i + 2]
    return got if many else (got[-1] if got else default)


def sha(p: Path) -> str:
    return hashlib.sha1(p.read_bytes()).hexdigest()


def slugs(labels: list) -> list:
    """The slug of every label, by _ep-slug.js — the one place the rule lives."""
    js = ("const S=require(process.argv[1]);const L=JSON.parse(require('fs').readFileSync(0,'utf8'));"
          "process.stdout.write(JSON.stringify(L.map(S.slug)));")
    r = subprocess.run(["node", "-e", js, str(SLUG_JS)], input=json.dumps(labels), capture_output=True, text=True)
    if r.returncode != 0:
        die(f"_ep-slug.js did not run under node: {r.stderr.strip()[-300:]}")
    return json.loads(r.stdout)


def c4_colors() -> tuple[dict, dict]:
    s = C4.read_text(encoding="utf-8")
    c4 = json.JSONDecoder().raw_decode(s, s.index("{"))[0]
    home = {n["id"]: slug for slug, g in c4["l2"].items() for n in g["nodes"]}
    return c4.get("colors") or {}, home


def write_manifest() -> dict:
    """_eps/built.js — what is in the directory now, read off the files themselves."""
    built = {}
    for p in sorted(EPS.glob("*.js")):
        if p.name == "built.js":
            continue
        with p.open(encoding="utf-8") as f:
            m = HEAD_RX.search(f.readline())
        built[p.stem] = m.group(1) if m else None
    rec = {"n": len(built), "heads": built}
    (EPS / "built.js").write_text("/* GENERATED by gen-endpoint-set.py — the facts files present in _eps/ (a local build, git-ignored). */\n"
                                  "window.LABEP_BUILT = " + json.dumps(rec, ensure_ascii=False, indent=1) + ";\n", encoding="utf-8")
    return rec


def main() -> int:
    argv = list(sys.argv[1:])
    forms = Path(arg(argv, "--forms", str(DEF_FORMS))).expanduser()
    archmap = Path(arg(argv, "--archmap", str(forms.parent / "archmap.json"))).expanduser()
    only = arg(argv, "--only", many=True)
    index_only = "--index-only" in argv
    if index_only:
        argv.remove("--index-only")
    if argv:
        die(f"unknown arguments: {argv}")
    for p in (forms, archmap, FACTS, SLUG_JS, C4):
        if not p.is_file():
            die(f"missing input: {p}")

    fj = json.loads(forms.read_text(encoding="utf-8"))
    if not fj.get("present"):
        die(f"{forms} holds no forms ({fj.get('reason')})")
    E = fj.get("endpoints") or {}
    keys = sorted(E)
    labels = [k.split(":", 1)[1] for k in keys]
    S = slugs(labels)
    clash = {s for s in S if S.count(s) > 1}
    if clash:
        die("two endpoints share a slug under _ep-slug.js's rule: " + ", ".join(f"{s} ← {[l for l, t in zip(labels, S) if t == s]}" for s in sorted(clash)))
    colors, home = c4_colors()
    rows = []
    for k, label, s in zip(keys, labels, S):
        ent = E[k].get("entity") or home.get(k)
        m, p = label.split(" ", 1)
        row = {"label": label, "m": m, "p": p, "ent": ent, "col": colors.get(ent), "slug": s}
        # the path the app MOUNTS it at, when the label's path is not it: a router whose prefix the label lost reads "/"
        # (four handlers of recipe_filter_modes.py, review 2026-09-23) — the feed's own full_path, the /api[/vN] mount
        # stripped as the web arm strips it; and the handler's file, so the picker can tell such rows apart and find them
        full = re.sub(r"^/api(?:/v\d+)?", "", E[k].get("full_path") or "") or None
        if full and full != p:
            row["mount"] = full
        if E[k].get("file"):
            row["file"] = E[k]["file"]
        rows.append(row)
    index = {"head": fj.get("head"), "n": len(rows), "slug_rule": "_ep-slug.js", "endpoints": rows}
    INDEX.write_text("/* GENERATED by gen-endpoint-set.py from the lab feed (head " + str(fj.get("head")) + ") — every endpoint the lab can open; "
                     "never edit, re-run the generator. */\nwindow.LABEP_INDEX = " + json.dumps(index, ensure_ascii=False, indent=1) + ";\n", encoding="utf-8")
    print(f"wrote {INDEX.relative_to(REPO)}: {len(rows)} endpoints @ {fj.get('head')}")
    if index_only:
        return 0

    targets = [(label, s) for label, s in zip(labels, S) if not only or label in only]
    if only:
        miss = [t for t in only if t not in labels]
        if miss:
            die(f"--only names endpoints the feed lacks: {miss}")
    EPS.mkdir(exist_ok=True)
    lab_before = sha(LAB) if LAB.is_file() else None
    t0, failed = time.time(), []
    for label, s in targets:
        out = EPS / (s + ".js")
        r = subprocess.run([sys.executable, str(FACTS), label, "--forms", str(forms), "--archmap", str(archmap), "--out", str(out)],
                           capture_output=True, text=True, cwd=str(HERE))
        if r.returncode != 0 or not out.is_file():
            failed.append((label, (r.stderr or r.stdout).strip()[-300:]))
    if (sha(LAB) if LAB.is_file() else None) != lab_before:
        die("_lab-ep.js changed while the set was built — the loop must never touch the lab's own file")
    rec = write_manifest()
    same = None
    dflt = EPS / "post-setup-complete.js"
    if LAB.is_file() and dflt.is_file():
        same = sha(dflt) == sha(LAB)
    print(f"built {len(targets) - len(failed)} of {len(targets)} into {EPS.relative_to(REPO)}/ in {time.time() - t0:.1f}s · "
          f"_eps/ now holds {rec['n']} · the default's file {'matches' if same else 'differs from' if same is False else 'is not beside'} _lab-ep.js")
    for label, why in failed:
        print(f"  FAILED {label}: {why}", file=sys.stderr)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
