#!/usr/bin/env python3
"""gen-help-catalog.py — regenerate gabe-help's Full Suite Catalog from skill frontmatter.

Kills the hand-kept-catalog drift class (trim-matrix #2): the table between the
CATALOG:BEGIN/END markers in skills/gabe-help/references/help-spec.md is written
by this script from the live skills/gabe-*/SKILL.md set + skills/_archive/.
Run by install.sh before copying (idempotent); never edit the table by hand.
"""
import re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "skills/gabe-help/references/help-spec.md"
BEGIN = "<!-- CATALOG:BEGIN — generated by scripts/gen-help-catalog.py; do not edit by hand -->"
END = "<!-- CATALOG:END -->"


def frontmatter_field(text: str, field: str) -> str:
    m = re.search(rf'^{field}:\s*"(.*?)"\s*$', text, re.M) or re.search(rf"^{field}:\s*(.+)$", text, re.M)
    return (m.group(1) if m else "").strip().strip('"')


def summarize(desc: str) -> tuple[str, str]:
    """Return (usage, summary) from a SKILL.md description field."""
    usage = ""
    if "Usage:" in desc:
        desc, usage = desc.split("Usage:", 1)
        usage = usage.strip().rstrip(".")
    # first sentence-ish (abbreviation-safe), escaped for a markdown table
    summary = desc.strip().rstrip(".")
    summary = re.split(r"(?<!\bincl)(?<!\be\.g)(?<!\bi\.e)(?<!\bvs)(?<=[a-z0-9\)\]`])\. ", summary, 1)[0]
    if len(summary) > 160:
        summary = summary[:157].rstrip() + "…"
    return usage.replace("|", "\\|"), summary.replace("|", "\\|")


def main() -> int:
    rows, archived = [], []
    for d in sorted(ROOT.glob("skills/gabe-*")):
        if not (d / "SKILL.md").is_file():  # a stray dir must not abort install.sh
            print(f"gen-help-catalog: WARNING — {d.name}/ has no SKILL.md, skipped", file=sys.stderr)
            continue
        text = (d / "SKILL.md").read_text(encoding="utf-8")
        name = (frontmatter_field(text, "name") or d.name).replace("|", "\\|")
        usage, summary = summarize(frontmatter_field(text, "description"))
        cmd = usage if usage.startswith("/") else f"/{name}"
        rows.append(f"| {name} | {cmd} | {summary} |")
    for d in sorted(ROOT.glob("skills/_archive/gabe-*")):
        archived.append(d.name)

    block = "\n".join(
        [
            BEGIN,
            "",
            f"The Gabe Suite — {len(rows)} skills (each skill IS its slash command).",
            "",
            "| Skill | Command | What it does |",
            "|------|---------|--------------|",
            *rows,
            "",
            (
                f"Archived (not installed; `skills/_archive/`): {', '.join(f'`{a}`' for a in archived)}."
                if archived
                else "Archived: none."
            ),
            "",
            END,
        ]
    )

    spec = SPEC.read_text(encoding="utf-8")
    if BEGIN not in spec or END not in spec:
        print(f"⛔ gen-help-catalog: markers missing in {SPEC} — refusing to guess placement", file=sys.stderr)
        return 1
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, spec, flags=re.S)
    if new != spec:
        SPEC.write_text(new, encoding="utf-8")
        print(f"gen-help-catalog: regenerated ({len(rows)} skills, {len(archived)} archived)")
    else:
        print(f"gen-help-catalog: up to date ({len(rows)} skills, {len(archived)} archived)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
