#!/usr/bin/env bash
# size-budget — deterministic gabe-commit gate check.
#
# WARNs when a touched first-party file is, or newly crosses, >800 lines. Generated files
# (identified by header markers) are exempt. Where the project's .kdbp/RULES.md or
# .kdbp/PENDING.md records split seams for the file, they are printed with the WARN.
#
# Zero model cost. Never blocks a commit by itself — WARNs feed the gate's triage.
#
# Usage: size-budget.sh [--cap N] [file...]
#   No file args → staged files (git diff --cached --name-only --diff-filter=ACMR).
# Exit: 0 = no warnings · 2 = warnings printed · 1 = usage/environment error.
set -u

CAP=800
FILES=()
while [ $# -gt 0 ]; do
  case "$1" in
    --cap) shift; CAP="${1:-800}" ;;
    -*) echo "size-budget: unknown flag $1" >&2; exit 1 ;;
    *) FILES+=("$1") ;;
  esac
  shift
done

git rev-parse --show-toplevel >/dev/null 2>&1 || { echo "size-budget: not a git repository" >&2; exit 1; }
ROOT="$(git rev-parse --show-toplevel)"

if [ ${#FILES[@]} -eq 0 ]; then
  while IFS= read -r f; do FILES+=("$f"); done < <(git diff --cached --name-only --diff-filter=ACMR)
fi
[ ${#FILES[@]} -eq 0 ] && exit 0

# Generated-file markers, checked in the first 10 lines (deterministic, header-based).
GEN_RE='@generated|Code generated|DO NOT EDIT|auto-generated|autogenerated|GENERATED FILE'

is_generated() { head -n 10 "$1" 2>/dev/null | grep -qiE "$GEN_RE"; }

print_seams() { # file-basename
  local base="$1" src hits
  for src in "$ROOT/.kdbp/RULES.md" "$ROOT/.kdbp/PENDING.md"; do
    [ -f "$src" ] || continue
    hits=$(grep -n -- "$base" "$src" 2>/dev/null | head -5)
    [ -n "$hits" ] && printf '    recorded seams (%s):\n%s\n' "${src#"$ROOT"/}" "$(echo "$hits" | sed 's/^/      /')"
  done
}

warned=0
for f in "${FILES[@]}"; do
  path="$ROOT/$f"
  [ -f "$path" ] || continue
  grep -qI '' "$path" 2>/dev/null || continue   # skip binary
  is_generated "$path" && continue

  now=$(wc -l < "$path")
  [ "$now" -le "$CAP" ] && continue

  before=$(git show "HEAD:$f" 2>/dev/null | wc -l)
  if [ "$before" -le "$CAP" ]; then
    if [ "$before" -eq 0 ]; then
      echo "SIZE-BUDGET WARN: $f — $now first-party lines (cap $CAP, new file over cap)"
    else
      echo "SIZE-BUDGET WARN: $f — $now first-party lines (cap $CAP, was $before — newly crossed)"
    fi
  else
    echo "SIZE-BUDGET WARN: $f — $now first-party lines (cap $CAP, was $before — still over)"
  fi
  print_seams "$(basename "$f")"
  warned=1
done

[ "$warned" -eq 1 ] && exit 2
exit 0
